name: cortada_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  build_runner: ^2.4.15
  dio: ^5.8.0+1
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_map: ^8.1.0
  flutter_riverpod: ^2.6.1
  geolocator: ^13.0.2
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.1
  google_sign_in: ^6.2.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  shared_preferences: ^2.5.2
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding.png
    - assets/images/logo.png
    - assets/images/google_icon.png
    - assets/images/volleyball_court.jpg
