// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWppe_F_kCFbH03Xdzq3xM8XfcyZvBow',
    appId: '1:632156050050:android:a7d2e3a8f5562c41795a9b',
    messagingSenderId: '632156050050',
    projectId: 'cortada-app-1dcad',
    storageBucket: 'cortada-app-1dcad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkUvNCJkkd4UTVe_QVBX8BSOKSAza4jvM',
    appId: '1:632156050050:ios:7e42e992982d2c75795a9b',
    messagingSenderId: '632156050050',
    projectId: 'cortada-app-1dcad',
    storageBucket: 'cortada-app-1dcad.firebasestorage.app',
    androidClientId: '632156050050-r6siatfal50aanlpjitf1d405avqvjot.apps.googleusercontent.com',
    iosClientId: '632156050050-26kirgth2oo2seujgoaltgltk45j14iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cortadaApp',
  );
}
